### ISSUE TITLE
Gradle dependency?

### ISSUE THREAD

**Issue by sbmaggarwal** [kedzie/DraggableDrawers#3]
How to use this library with Gradle?

**Comment by omegadrh** [comment]
I believe the groundwork for this has been laid in commit 1bd7cfeebbcc6c3a7b3b9e0111e91dfcd2f07916, but hasn't propagated to the (an) actual Maven repository yet.

As a workaround until this can be pushed to Maven (at which point you'll be able to just add something like `compile 'com.github.kedzie.draggabledrawers:library:1.0.1'` to your build.gradle dependencies), my project just copied the code locally and builds it as a library (`apply plugin: 'com.android.library'` in the DraggableDrawers build.gradle file, and in the project using DD, something like `compile project(':draggerLibrary')`).

**Comment by kedzie** [comment]
I actually did add gradle scripts recently, I will make sure it is all
pushed up.  But you can also use maven to install the artifacts into your
local maven repo, then import them into your gradle project.  Just make
sure you add the mavenLocal repository.
